# Generated by Django 4.1.7 on 2023-03-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliveries",
            fields=[
                ("delivery_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("match_id", models.IntegerField()),
                ("inning_id", models.IntegerField(blank=True, null=True)),
                ("batsman_id", models.IntegerField()),
                ("bowler_id", models.IntegerField()),
                ("non_striker_id", models.IntegerField()),
                ("ball_number", models.IntegerField(blank=True, null=True)),
                ("over_number", models.IntegerField(blank=True, null=True)),
                ("runs_scored", models.IntegerField(blank=True, null=True)),
                ("extra_runs", models.IntegerField(blank=True, null=True)),
                ("is_wicket", models.BooleanField(blank=True, null=True)),
                ("player_out", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dismissal_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fielder_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "deliveries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Matches",
            fields=[
                ("match_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("match_type", models.CharField(blank=True, max_length=255, null=True)),
                ("series_id", models.BigIntegerField(blank=True, null=True)),
                ("match_date", models.DateField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("toss_winner", models.BigIntegerField()),
                (
                    "toss_decision",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("result", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "matches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MatchesInnings",
            fields=[
                ("inning_id", models.AutoField(primary_key=True, serialize=False)),
                ("innings_number", models.IntegerField(blank=True, null=True)),
                (
                    "team_batted",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "matches_innings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                ("player_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "batting_style",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bowling_style",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "player_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "player_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "players",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                ("series_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "series_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("season", models.CharField(blank=True, max_length=255, null=True)),
                ("match_id_set_text", models.TextField(blank=True, null=True)),
                ("series_start_date", models.DateField(blank=True, null=True)),
                ("series_end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "series",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                ("team_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255, unique=True)),
                (
                    "team_short_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "team_logo_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("team_captain", models.BigIntegerField(blank=True, null=True)),
                ("team_coach", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "teams",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Innings",
            fields=[
                (
                    "batting_team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="home.teams",
                    ),
                ),
                ("total_runs", models.IntegerField(blank=True, null=True)),
                ("wickets_lost", models.IntegerField(blank=True, null=True)),
                ("innings_number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "innings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="home.players",
                    ),
                ),
                ("matches_played", models.IntegerField(blank=True, null=True)),
                ("runs_scored", models.IntegerField(blank=True, null=True)),
                ("balls_faced", models.IntegerField(blank=True, null=True)),
                ("strike_rate", models.FloatField(blank=True, null=True)),
                ("hundreds", models.IntegerField(blank=True, null=True)),
                ("fifties", models.IntegerField(blank=True, null=True)),
                ("best_score", models.IntegerField(blank=True, null=True)),
                ("wickets_taken", models.IntegerField(blank=True, null=True)),
                ("economy", models.FloatField(blank=True, null=True)),
                ("five_wickets", models.IntegerField(blank=True, null=True)),
                ("ten_wickets", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "player_stats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeriesMatches",
            fields=[
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="home.matches",
                    ),
                ),
                ("match_number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "series_matches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TeamStats",
            fields=[
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="home.teams",
                    ),
                ),
                ("matches_played", models.IntegerField(blank=True, null=True)),
                ("matches_won", models.IntegerField(blank=True, null=True)),
                ("matches_lost", models.IntegerField(blank=True, null=True)),
                ("matches_tied", models.IntegerField(blank=True, null=True)),
                ("matches_drawn", models.IntegerField(blank=True, null=True)),
                ("total_runs_scored", models.IntegerField(blank=True, null=True)),
                ("total_wickets_lost", models.IntegerField(blank=True, null=True)),
                ("total_overs_bowled", models.IntegerField(blank=True, null=True)),
                ("total_overs_faced", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "team_stats",
                "managed": False,
            },
        ),
    ]
