# Generated by Django 4.1.7 on 2023-03-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Moviesss",
            new_name="Movies",
        ),
    ]
